/// <reference types="vite/client" />
'use client';
import{useEffect,useRef,useState}from'react';
import * as T from'three';
import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';
import{DRACOLoader}from'three/addons/loaders/DRACOLoader.js';
import{OrbitControls}from'three/addons/controls/OrbitControls.js';
import{RotateCcw,Plus,Minus,Maximize,Pause,Play,Layers,Tags,Network}from'lucide-react';
import{regions}from'./data';
export default function BrainScene({selected,onSelect,explorer=false}:{selected:string|null;onSelect:(s:string)=>void;explorer?:boolean}){
const host=useRef<HTMLDivElement>(null),api=useRef<any>(null),latest=useRef({selected,onSelect});latest.current={selected,onSelect};
const[unavailable,setUnavailable]=useState(false);const[status,setStatus]=useState('Loading anatomical model…'),[hover,setHover]=useState(''),[labels,setLabels]=useState(true),[glass,setGlass]=useState(false),[neural,setNeural]=useState(false),[spin,setSpin]=useState(false),[medial,setMedial]=useState(false);
useEffect(()=>{let alive=true,raf=0;const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});}catch{setUnavailable(true);setStatus('3D requires WebGL. You can still explore every region using the anatomy list.');return;}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;setSpin(!reduced);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.22;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive anatomical brain. Drag to rotate. Use the labeled controls to zoom and choose a view.');
const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.01,100),controls=new OrbitControls(camera,renderer.domElement);camera.position.set(5.4,1.6,3.9);controls.enableDamping=!reduced;controls.dampingFactor=.08;controls.enablePan=false;controls.minDistance=3.8;controls.maxDistance=10;controls.autoRotate=!reduced;controls.autoRotateSpeed=.28;controls.target.set(0,0,0);controls.update();scene.add(new T.HemisphereLight(0xb7dbff,0x082030,2));for(const[c,i,p]of [[0xc8e8ff,3,[-3,5,5]],[0x78baff,2.8,[4,1,-3]],[0xa69bff,1,[-3,-1,-4]]] as any){const l=new T.DirectionalLight(c,i);l.position.set(p[0],p[1],p[2]);scene.add(l);}
const root=new T.Group();scene.add(root);const meshes:T.Mesh[]=[];const anchors:Record<string,T.Vector3>={};const draco=new DRACOLoader();draco.setDecoderPath(new URL('draco/',document.baseURI).href);const loader=new GLTFLoader();loader.setDRACOLoader(draco);const state={glass:false,neural:false,medial:false,hover:'',view:'lateral',focus:null as T.Vector3|null};
loader.load(new URL('models/brain.glb',document.baseURI).href,g=>{if(!alive){g.scene.traverse((o:any)=>{o.geometry?.dispose()});return;}g.scene.updateMatrixWorld(true);const bounds=new T.Box3();g.scene.traverse((o:any)=>{if(o.isMesh){const d=o.userData?.bx_cat?o.userData:o.parent?.userData||{};o.userData={...d};if(['cortex','cerebellum','brainstem'].includes(d.bx_cat))bounds.expandByObject(o);}});const center=bounds.getCenter(new T.Vector3()),size=bounds.getSize(new T.Vector3());g.scene.position.sub(center);root.add(g.scene);root.scale.setScalar(3.55/Math.max(size.x,size.y,size.z));g.scene.traverse((o:any)=>{if(!o.isMesh)return;const d=o.userData,r=regions.find(r=>r.id===d.bx_region||r.id==='Brainstem'&&d.bx_cat==='brainstem'||r.id==='Cerebellum'&&d.bx_cat==='cerebellum');d.region=r?.id||null;const color=r?.color||(d.bx_cat==='tracts'?'#7be8ec':'#96b7cf');const oldMaterials=Array.isArray(o.material)?o.material:[o.material];oldMaterials.forEach((m:T.Material)=>m.dispose());o.material=new T.MeshPhysicalMaterial({color,emissive:color,emissiveIntensity:.04,roughness:.48,metalness:.08,clearcoat:.36});meshes.push(o);});root.updateMatrixWorld(true);for(const r of regions){const b=new T.Box3();meshes.filter(m=>m.userData.region===r.id).forEach(m=>b.expandByObject(m));if(!b.isEmpty())anchors[r.id]=b.getCenter(new T.Vector3());}if(latest.current.selected)api.current?.focus(latest.current.selected);setStatus('');},undefined,()=>{if(alive){setUnavailable(true);setStatus('The 3D model could not load. Reload the page to retry; the anatomy descriptions remain available.');}});
const ray=new T.Raycaster(),pointer=new T.Vector2();let start={x:0,y:0};const hit=(e:PointerEvent)=>{const b=el.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(meshes.filter(m=>m.visible&&m.userData.region))[0]?.object.userData.region||'';};const move=(e:PointerEvent)=>{if(e.buttons)return;state.hover=hit(e);setHover(state.hover);renderer.domElement.style.cursor=state.hover?'pointer':'grab';};const down=(e:PointerEvent)=>{start={x:e.clientX,y:e.clientY};controls.autoRotate=false;setSpin(false);};const up=(e:PointerEvent)=>{if(Math.hypot(start.x-e.clientX,start.y-e.clientY)<7){const r=hit(e);if(r)latest.current.onSelect(r);}};const leave=()=>{state.hover='';setHover('')};renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointerleave',leave);
const ro=new ResizeObserver(()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();});ro.observe(el);let visible=true;const io=new IntersectionObserver(e=>visible=e[0].isIntersecting);io.observe(el);const animate=(time:number)=>{raf=requestAnimationFrame(animate);if(!visible||document.hidden)return;const active=state.hover||latest.current.selected;for(const m of meshes){const d=m.userData,mat=m.material as T.MeshPhysicalMaterial;const core=['cortex','cerebellum','brainstem','white_matter','diencephalon','deep_grey'].includes(d.bx_cat);m.visible=(core||state.neural&&d.bx_cat==='tracts')&&!(state.medial&&d.bx_side==='left');const dim=!!active&&d.region!==active;const transparent=state.glass&&d.bx_cat==='cortex';if(mat.transparent!==transparent){mat.transparent=transparent;mat.needsUpdate=true;}mat.opacity=mat.transparent?.23:1;mat.depthWrite=!mat.transparent;mat.color.set(regions.find(r=>r.id===d.region)?.color||(d.bx_cat==='tracts'?'#75f8ff':'#7eabc8')).multiplyScalar(dim?.46:1);mat.emissiveIntensity=d.bx_cat==='tracts'?.7:active===d.region?.15+(reduced?0:Math.sin(time*.003)*.05):.025;}
if(state.focus){controls.target.lerp(state.focus,reduced?1:.06);}controls.update();for(const r of regions){const pt=anchors[r.id]?.clone().project(camera),label=el.parentElement?.querySelector('[data-label="'+r.id+'"]') as HTMLElement,line=el.parentElement?.querySelector('[data-leader="'+r.id+'"]');if(pt&&label&&line){const left=label.offsetLeft<el.clientWidth/2;line.setAttribute('x1',String(label.offsetLeft+(left?label.offsetWidth:0)));line.setAttribute('y1',String(label.offsetTop+label.offsetHeight/2));line.setAttribute('x2',String((pt.x*.5+.5)*el.clientWidth));line.setAttribute('y2',String((-.5*pt.y+.5)*el.clientHeight));}}renderer.render(scene,camera);};raf=requestAnimationFrame(animate);
api.current={state,controls,camera,reset(){state.focus=new T.Vector3();camera.position.set(5.4,1.6,3.9);controls.target.set(0,0,0);},focus(id:string){root.updateMatrixWorld(true);const b=new T.Box3();meshes.filter(m=>m.userData.region===id).forEach(m=>b.expandByObject(m));if(!b.isEmpty())state.focus=b.getCenter(new T.Vector3()).multiplyScalar(.35);},zoom(f:number){camera.position.sub(controls.target).multiplyScalar(f).clampLength(3.8,10).add(controls.target);}};
return()=>{alive=false;cancelAnimationFrame(raf);ro.disconnect();io.disconnect();controls.dispose();draco.dispose();meshes.forEach(m=>{m.geometry.dispose();(m.material as T.Material).dispose();});renderer.dispose();renderer.domElement.remove();api.current=null;};},[]);
useEffect(()=>{if(api.current){api.current.state.glass=glass;api.current.state.neural=neural;api.current.state.medial=medial;api.current.controls.autoRotate=spin; }},[glass,neural,medial,spin]);useEffect(()=>{api.current?.camera.position.set(...(medial?[5.8,.8,.1] as const:[5.4,1.6,3.9] as const));},[medial]);useEffect(()=>{if(selected)api.current?.focus(selected)},[selected]);
const toggleFullscreen=()=>{const e=host.current!.parentElement!;if(document.fullscreenElement)document.exitFullscreen();else e.requestFullscreen?.().catch(()=>setStatus('Fullscreen is unavailable in this browser.'));};
return <div className={'brain-stage '+(explorer?'large':'')}><div ref={host} className="webgl"/>{unavailable&&<img className="brain-poster" src="brain-poster.webp" alt="Rendered preview of the anatomical 3D brain model"/>}{status&&<div className={"model-status "+(unavailable?"unavailable":"")} role="status">{status}</div>}<div className="stage-meta"><span>HUMAN BRAIN</span><span>ANATOMICAL ATLAS / 01</span></div>{labels&&(!status||unavailable)&&<div className="annotations">{!unavailable&&<svg className="leaders" aria-hidden="true">{regions.map(r=><line key={r.id} data-leader={r.id} stroke={r.color}/>)}</svg>}{regions.map((r,i)=><button key={r.id} data-label={r.id} className={'annotation an-'+i+(hover===r.id||selected===r.id?' lit':'')} style={{'--region':r.color} as any} onClick={()=>onSelect(r.id)}><span>{r.name}</span>{unavailable&&<i/>}</button>)}</div>}{hover&&<div className="brain-tooltip" role="status"><strong>{hover}</strong><span>{regions.find(r=>r.id===hover)?.summary}</span></div>}<div className="stage-bottom"><span>{unavailable?"SELECT A LABEL TO LEARN":"DRAG TO ROTATE · SCROLL TO ZOOM"}</span><span>{unavailable?"STATIC PREVIEW":"3D / LIVE"}</span></div><div hidden={unavailable} className="brain-toolbar" role="toolbar" aria-label="Brain controls">{[[spin?Pause:Play,'Auto rotate',spin,()=>setSpin(!spin)],[RotateCcw,'Reset camera',false,()=>{setMedial(false);setSpin(false);api.current?.reset()}],[Minus,'Zoom out',false,()=>api.current?.zoom(1.15)],[Plus,'Zoom in',false,()=>api.current?.zoom(.87)],[Layers,'Transparent cortex',glass,()=>setGlass(!glass)],[Tags,'Show labels',labels,()=>setLabels(!labels)],[Network,'Neural pathways',neural,()=>setNeural(!neural)],[Maximize,'Fullscreen',false,toggleFullscreen]].map(([Icon,title,on,fn]:any)=><button key={title} title={title} aria-label={title} aria-pressed={on} className={on?'on':''} onClick={fn}><Icon size={17}/></button>)}</div>{explorer&&!unavailable&&<div className="view-tabs"><button aria-pressed={!medial} onClick={()=>setMedial(false)}>Lateral</button><button aria-pressed={medial} onClick={()=>setMedial(true)}>Medial cutaway</button></div>}</div>;
}
