export const regions=[
{id:'Frontal lobe',name:'Frontal Lobe',color:'#63caff',summary:'Thinking ahead. Turning intentions into action.',desc:'The frontal lobe supports planning, decision-making, voluntary movement and aspects of language. These abilities emerge from networks that work with other parts of the brain.',functions:['Planning & decision-making','Voluntary movement','Speech production'],fact:'The primary motor cortex lies in the precentral gyrus, just in front of the central sulcus.'},
{id:'Parietal lobe',name:'Parietal Lobe',color:'#55dfb1',summary:'Making sense of your body and the space around it.',desc:'The parietal lobe integrates touch and other sensory signals. It helps locate your body in space and supports attention, number processing and visually guided action.',functions:['Touch & body sensation','Spatial awareness','Sensory integration'],fact:'The primary somatosensory cortex sits just behind the central sulcus.'},
{id:'Temporal lobe',name:'Temporal Lobe',color:'#e7b964',summary:'Connecting sound, language and memory.',desc:'Temporal regions contribute to hearing, language comprehension, object recognition and memory. The medial temporal structures, including the hippocampus, help form new episodic memories.',functions:['Auditory processing','Language comprehension','Memory formation'],fact:'The hippocampus is a medial temporal structure, tucked beneath the cortex.'},
{id:'Occipital lobe',name:'Occipital Lobe',color:'#ae8ff8',summary:'Transforming incoming signals into vision.',desc:'At the back of the brain, the occipital lobe processes visual signals. Its interconnected areas help analyze edges, color and motion before sharing information with wider networks.',functions:['Visual processing','Form & color','Visual motion'],fact:'The primary visual cortex lies around the calcarine sulcus on the medial surface.'},
{id:'Cerebellum',name:'Cerebellum',color:'#e69ab9',summary:'Fine-tuning movement, balance and learning.',desc:'The cerebellum compares intended movements with sensory feedback and helps refine their timing and precision. It also participates in motor learning and wider cognitive networks.',functions:['Balance & posture','Movement coordination','Motor learning'],fact:'Although smaller than the cerebrum, the cerebellum contains the majority of the brain’s neurons.'},
{id:'Brainstem',name:'Brain Stem',color:'#6dd9dc',summary:'A vital connection between brain and body.',desc:'The midbrain, pons and medulla form the brainstem. They relay signals between the brain and spinal cord and contain circuits involved in breathing, arousal and cardiovascular regulation.',functions:['Breathing regulation','Sleep & arousal','Brain–body communication'],fact:'Many cranial nerves connect to the brainstem.'}
];
export const studies=[
{date:'May 9, 2024',category:'Connectomics',title:'A tiny piece of brain. An extraordinary map.',desc:'A nanoscale reconstruction of one cubic millimeter of human cortex reveals an intricate landscape of cells and connections.',url:'https://www.science.org/doi/10.1126/science.adk4858',tag:'Human cortex · Electron microscopy'},
{date:'October 2, 2024',category:'Connectomics',title:'Mapping an entire adult fruit fly brain',desc:'A complete wiring diagram offers a powerful resource for studying how neural circuits support behavior. This is an animal model, not a human brain map.',url:'https://www.nature.com/articles/s41586-024-07558-y',tag:'Drosophila · Neural circuits'},
{date:'October 12, 2023',category:'Cell biology',title:'The cellular diversity of the human brain',desc:'Single-cell approaches reveal a rich diversity of cell types across adult human brain regions.',url:'https://www.science.org/doi/10.1126/science.add7046',tag:'Human brain · Cell atlas'},
{date:'Learning guide',category:'Sleep & memory',title:'Why the sleeping brain stays busy',desc:'Explore sleep stages and how sleep supports memory and the communication between nerve cells.',url:'https://www.ninds.nih.gov/health-information/public-education/brain-basics/brain-basics-understanding-sleep',tag:'NINDS · Educational overview'}];
export const disorders=[
{name:'Alzheimer’s disease',category:'Memory',desc:'A progressive brain disorder that affects memory, thinking and daily functioning.',url:'https://www.nia.nih.gov/health/alzheimers-and-dementia'},
{name:'Parkinson’s disease',category:'Movement',desc:'A neurological condition that can affect movement, sleep, mood and other functions.',url:'https://www.ninds.nih.gov/health-information/disorders/parkinsons-disease'},
{name:'Depression',category:'Mood',desc:'A mood disorder involving persistent changes in mood, interest and everyday functioning. Many biological and environmental factors contribute.',url:'https://www.nimh.nih.gov/health/topics/depression'},
{name:'Narcolepsy',category:'Sleep',desc:'A neurological disorder affecting the brain’s regulation of sleep and wakefulness.',url:'https://www.ninds.nih.gov/health-information/disorders/narcolepsy'},
{name:'Autism spectrum disorder',category:'Development',desc:'A neurodevelopmental condition associated with differences in communication, interaction and patterns of behavior. Experiences and support needs vary.',url:'https://www.nimh.nih.gov/health/topics/autism-spectrum-disorders-asd'},
{name:'Amyotrophic lateral sclerosis',category:'Neurodegenerative',desc:'A progressive disease that affects nerve cells controlling voluntary muscles.',url:'https://www.ninds.nih.gov/health-information/disorders/amyotrophic-lateral-sclerosis-als'}];
export const glossary=[['Axon','A nerve-cell extension that carries signals toward other cells.'],['Cortex','The outer layer of the cerebrum, composed of folded gray matter.'],['Gyrus','A ridge or fold on the surface of the cerebral cortex.'],['Neuron','A specialized cell that communicates using electrical and chemical signals.'],['Neuroplasticity','The nervous system’s capacity to change its structure and function with experience.'],['Synapse','A junction where one neuron communicates with another cell.'],['Sulcus','A groove between folds of the cerebral cortex.'],['White matter','Brain tissue rich in axons, many insulated by myelin.']];
