'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {RotateCcw,Plus,Minus,Play,Pause,Layers,Maximize,ArrowUpRight} from 'lucide-react';
const parts=[
{id:'soma',name:'Cell body',sub:'Soma · the metabolic center',text:'The cell body sustains the neuron and integrates inputs arriving through its dendrites. Its membrane continues into the branching processes.',color:'#d9a594'},
{id:'dendrites',name:'Dendrites',sub:'A branching receptive surface',text:'Tapering dendrites receive signals from other cells. Small dendritic spines create additional sites for synaptic contact; their shapes and density vary between neurons.',color:'#e4b6a1'},
{id:'nucleus',name:'Nucleus',sub:'Genetic information within',text:'The nucleus contains most of the cell’s DNA and helps regulate gene expression. Use the cutaway control to see it inside the cell body.',color:'#bb91ad'},
{id:'axon',name:'Axon',sub:'The outgoing signal pathway',text:'A single axon emerges from the cell body and carries action potentials toward its terminal branches. Its length is compressed here to keep the entire cell explorable.',color:'#c99b7e'},
{id:'myelin',name:'Myelin sheath',sub:'Insulation around the axon',text:'Layers of glial-cell membrane wrap segments of many axons. This insulation supports rapid signal conduction. Not all neurons have myelinated axons.',color:'#e6d8be'},
{id:'nodes',name:'Nodes of Ranvier',sub:'Small gaps. Essential function.',text:'Gaps between myelin segments expose the axonal membrane. Action potentials are regenerated at these nodes during saltatory conduction.',color:'#c8956e'},
{id:'terminals',name:'Axon terminals',sub:'Where cells communicate',text:'Fine terminal branches end in boutons. At chemical synapses, these endings release neurotransmitters that act on a receiving cell across a tiny synaptic cleft.',color:'#d5aa91'}];
export default function NeuronScene(){
const host=useRef<HTMLDivElement>(null),api=useRef<any>(null);const[selected,select]=useState('soma'),[cutaway,setCutaway]=useState(false),[spin,setSpin]=useState(false),[signal,setSignal]=useState(false),[error,setError]=useState('');const current=useRef({selected,cutaway,spin,signal});current.current={selected,cutaway,spin,signal};
useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch{setError('Your browser cannot start 3D. Try enabling hardware acceleration. You can still read every structure below.');return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.setClearColor(0x071318,1);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive three-dimensional neuron. Drag to rotate, pinch to zoom, or select a structure from the list.');
const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,180),controls=new OrbitControls(camera,renderer.domElement);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;controls.enableDamping=!reduced;controls.minDistance=5;controls.maxDistance=75;controls.autoRotateSpeed=.32;controls.enablePan=true;const target=new T.Vector3(1.2,0,0);let focus:T.Vector3|null=null;function reset(){focus=null;controls.target.copy(target);camera.position.set(1.2,4,30);if(el.clientWidth<600)camera.position.z=62;controls.update();}reset();
scene.add(new T.HemisphereLight(0xd6e6e5,0x443128,1.9));for(const [c,intensity,p] of [[0xffdfc8,3.6,[-7,9,10]],[0x77c9d1,2.6,[5,1,-7]],[0xdba8a0,1,[-8,-5,4]]] as const){const light=new T.DirectionalLight(c,intensity);light.position.set(p[0],p[1],p[2]);scene.add(light);}
let seed=917;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
const textureCanvas=document.createElement('canvas');textureCanvas.width=textureCanvas.height=256;const ctx=textureCanvas.getContext('2d')!,pixels=ctx.createImageData(256,256);for(let i=0;i<pixels.data.length;i+=4){const n=90+random()*100;pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=n;pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);const bump=new T.CanvasTexture(textureCanvas);bump.wrapS=bump.wrapT=T.RepeatWrapping;bump.repeat.set(3,3);
const geometries:Record<string,T.BufferGeometry[]>={};const meshes:Record<string,T.Mesh>={};const add=(id:string,g:T.BufferGeometry)=>{g.deleteAttribute('uv');(geometries[id]??=[]).push(g);};
// Parallel-transport frames keep curved, tapering neurites circular in three dimensions.
function tube(id:string,curve:T.CatmullRomCurve3,r0:number,r1:number,steps=24,sides=9){const frames=curve.computeFrenetFrames(steps,false),p:number[]=[],indices:number[]=[];for(let i=0;i<=steps;i++){const t=i/steps,c=curve.getPointAt(t),r=(r1+(r0-r1)*Math.pow(1-t,1.25))*(1+.065*Math.sin(t*29+r0*15));for(let j=0;j<=sides;j++){const a=j/sides*Math.PI*2,q=c.clone().addScaledVector(frames.normals[i],Math.cos(a)*r).addScaledVector(frames.binormals[i],Math.sin(a)*r);p.push(q.x,q.y,q.z);if(i<steps&&j<sides){const n=i*(sides+1)+j;indices.push(n,n+sides+1,n+1,n+1,n+sides+1,n+sides+2);}}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setIndex(indices);g.computeVertexNormals();add(id,g);}
function blob(id:string,pos:T.Vector3,scale:T.Vector3,detail=20){const g=new T.SphereGeometry(1,detail,Math.round(detail*.75));const a=g.attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i),y=a.getY(i),z=a.getZ(i);const n=1+.045*Math.sin(x*13+y*9)*Math.cos(z*11-y*7)+.018*Math.sin(x*43+z*31);a.setXYZ(i,x*n,y*n,z*n);}g.scale(scale.x,scale.y,scale.z);g.translate(pos.x,pos.y,pos.z);g.computeVertexNormals();add(id,g);}
const soma=V(-3,0,0);blob('soma',soma,V(1.25,1.02,.86),96);blob('nucleus',V(-3,.02,.2),V(.56,.49,.48),48);blob('nucleus',V(-2.84,.1,.64),V(.14,.12,.1),20);
function branch(start:T.Vector3,dir:T.Vector3,len:number,r:number,depth:number){const end=start.clone().addScaledVector(dir,len),bend=V((random()-.5)*len*.38,(random()-.5)*len*.38,(random()-.5)*len*.6);const curve=new T.CatmullRomCurve3([start,start.clone().lerp(end,.32).add(bend),start.clone().lerp(end,.72).addScaledVector(bend,-.4),end]);tube('dendrites',curve,r,depth?r*.49:.009,20,8);if(depth<=2){for(let i=0;i<5;i++){const t=.2+random()*.72,p=curve.getPointAt(t),out=V(random()-.5,random()-.5,random()-.5).normalize(),tip=p.clone().addScaledVector(out,.10+random()*.13);tube('dendrites',new T.CatmullRomCurve3([p,p.clone().lerp(tip,.6),tip]),.014,.01,4,5);blob('dendrites',tip,V(.035,.045,.035),8);}}if(depth>0){for(const sign of [-1,1]){const next=dir.clone().add(V(sign*(.22+random()*.48),sign*(.2+random()*.45),(random()-.5)*.9)).normalize();branch(end,next,len*(.62+random()*.18),r*.51,depth-1);}}}
for(let i=0;i<8;i++){const angle=(i/8)*Math.PI*2+.18;const dir=V(Math.cos(angle),Math.sin(angle),(random()-.5)*.9).normalize();if(dir.x>.8)dir.y+=.8;dir.normalize();branch(soma.clone().addScaledVector(dir,.68),dir,1.55+random()*.65,.34,4);}
const axon=new T.CatmullRomCurve3([V(-2.15,-.34,.02),V(-1.1,-1,.15),V(.3,-1.65,.35),V(2.4,-1.58,.1),V(4.9,-2,.42),V(7.3,-1.65,.15),V(9,-2.1,0)]);tube('axon',axon,.16,.09,160,14);
for(let i=0;i<7;i++){const from=.2+i*.105,to=from+.088,pts=Array.from({length:18},(_,j)=>axon.getPointAt(from+(to-from)*j/17));const curve=new T.CatmullRomCurve3(pts);tube('myelin',curve,.245,.215,24,18);for(const t of [from,to]){const p=axon.getPointAt(t);const ring=new T.TorusGeometry(.164,.04,8,22);ring.applyMatrix4(new T.Matrix4().makeRotationFromQuaternion(new T.Quaternion().setFromUnitVectors(V(0,0,1),axon.getTangentAt(t))));ring.translate(p.x,p.y,p.z);add('myelin',ring);}if(i<6){const p=axon.getPointAt(to+.008);blob('nodes',p,V(.12,.12,.12),14);}}
function terminal(start:T.Vector3,dir:T.Vector3,len:number,depth:number){const end=start.clone().addScaledVector(dir,len),mid=start.clone().lerp(end,.5).add(V(0,(random()-.5)*.4,(random()-.5)*.4));tube('terminals',new T.CatmullRomCurve3([start,mid,end]),depth?.065:.028,depth?.035:.016,15,7);if(depth){for(const sign of [-1,1])terminal(end,dir.clone().add(V(.1,sign*.65,(random()-.5)*1.4)).normalize(),len*.7,depth-1);}else blob('terminals',end,V(.1,.085,.08),14);}terminal(axon.getPointAt(1),V(.7,.4,.1).normalize(),1.3,3);
for(const part of parts){const g=mergeGeometries(geometries[part.id]);geometries[part.id].forEach(x=>x.dispose());if(!g)continue;const mat=new T.MeshPhysicalMaterial({color:part.color,roughness:.64,metalness:0,clearcoat:.14,clearcoatRoughness:.7,emissive:part.color,emissiveIntensity:0});
// Object-space membrane relief avoids obvious UV seams on merged organic branches.
mat.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 tissueP;').replace('#include <begin_vertex>','#include <begin_vertex>\ntissueP = position;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 tissueP;').replace('#include <normal_fragment_maps>','#include <normal_fragment_maps>\nfloat grain=sin(tissueP.x*83.0+sin(tissueP.z*61.0))*sin(tissueP.y*97.0+tissueP.z*53.0); normal=normalize(normal+0.065*vec3(grain,sin(tissueP.z*109.0),sin(tissueP.y*113.0)));').replace('#include <color_fragment>','#include <color_fragment>\ndiffuseColor.rgb *= 0.95 + 0.05*sin(tissueP.x*31.0)*sin(tissueP.y*37.0)*sin(tissueP.z*29.0);');};const mesh=new T.Mesh(g,mat);mesh.userData.part=part.id;scene.add(mesh);meshes[part.id]=mesh;}
const pulse=new T.Mesh(new T.SphereGeometry(.17,16,12),new T.MeshBasicMaterial({color:0x8cffff}));scene.add(pulse);pulse.visible=false;let signalStart=0;
const ray=new T.Raycaster(),pointer=new T.Vector2();let down=[0,0];const onDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY];setSpin(false);focus=null;};const onUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(Object.values(meshes).filter(m=>m.visible&&(m.userData.part!=='soma'||!current.current.cutaway)))[0];if(hit){const id=hit.object.userData.part;select(id);if(id==='nucleus')setCutaway(true);}};renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',onUp);
const resize=new ResizeObserver(()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);});resize.observe(el);let visible=true;const observer=new IntersectionObserver(es=>visible=es[0].isIntersecting);observer.observe(el);let frame=0;
api.current={reset,zoom(f:number){camera.position.sub(controls.target).multiplyScalar(f).clampLength(5,75).add(controls.target);},focus(id:string){if(!meshes[id])return;const box=new T.Box3().setFromObject(meshes[id]);focus=box.getCenter(new T.Vector3()).lerp(target,.45);},signal(){signalStart=performance.now();}};
const animate=(time:number)=>{frame=requestAnimationFrame(animate);if(!visible||document.hidden)return;controls.autoRotate=current.current.spin;const s=current.current;for(const [id,mesh] of Object.entries(meshes)){const mat=mesh.material as T.MeshPhysicalMaterial;mat.emissiveIntensity=id===s.selected?.1:0;if(id==='soma'){const translucent=s.cutaway;if(mat.transparent!==translucent){mat.transparent=translucent;mat.depthWrite=!translucent;mat.needsUpdate=true;}mat.opacity=translucent?.16:1;}if(id==='nucleus')mesh.visible=s.cutaway;}
if(focus)controls.target.lerp(focus,reduced?1:.05);pulse.visible=s.signal; if(s.signal)pulse.position.copy(axon.getPointAt(((time-signalStart)%5000)/5000));controls.update();renderer.render(scene,camera);};frame=requestAnimationFrame(animate);
return()=>{cancelAnimationFrame(frame);resize.disconnect();observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',onDown);renderer.domElement.removeEventListener('pointerup',onUp);Object.values(meshes).forEach(m=>{m.geometry.dispose();(m.material as T.Material).dispose();});pulse.geometry.dispose();(pulse.material as T.Material).dispose();bump.dispose();renderer.dispose();renderer.domElement.remove();api.current=null;};},[]);
const part=parts.find(p=>p.id===selected)!;const pick=(id:string)=>{select(id);if(id==='nucleus')setCutaway(true);api.current?.focus(id);};
return <section className="neuron-section"><div className="page-heading"><span className="eyebrow">FROM ANATOMY TO THE SINGLE CELL</span><h1>Interactive 3D Neuron</h1><p>A closer encounter with the living architecture of a nerve cell.</p></div><div className="neuron-layout"><div className="neuron-view"><div className="neuron-canvas" ref={host}/><div className="neuron-meta"><span>CELLULAR ATLAS / 02</span><strong>Multipolar neuron</strong><small>Natural tissue palette · 3D reconstruction</small></div>{error&&<p className="neuron-error" role="status">{error}</p>}<div className="neuron-legend"><i/> {part.name}<span>DRAG TO ROTATE · PINCH TO ZOOM</span></div><div className="neuron-tools" role="toolbar" aria-label="Neuron controls">{[[RotateCcw,'Reset view',false,()=>{setSpin(false);api.current?.reset()}],[Minus,'Zoom out',false,()=>api.current?.zoom(1.18)],[Plus,'Zoom in',false,()=>api.current?.zoom(.84)],[spin?Pause:Play,'Auto rotate',spin,()=>setSpin(!spin)],[Layers,'Cell body cutaway',cutaway,()=>setCutaway(!cutaway)],[Maximize,'Fullscreen',false,()=>{const node=host.current?.parentElement;if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else node?.requestFullscreen?.().catch(()=>setError('Fullscreen is unavailable in this browser.'));}]].map(([Icon,label,on,fn]:any)=><button key={label} title={label} aria-label={label} aria-pressed={on} onClick={fn}><Icon size={18}/></button>)}</div></div><aside className="neuron-panel glass"><span className="eyebrow">EXPLORE THE STRUCTURES</span><div className="neuron-parts">{parts.map((p,i)=><button key={p.id} aria-pressed={p.id===selected} onClick={()=>pick(p.id)}><span style={{background:p.color}}/><strong>{p.name}</strong><small>0{i+1}</small></button>)}</div><div className="neuron-detail" aria-live="polite"><span className="eyebrow">{part.sub}</span><h2>{part.name}</h2><p>{part.text}</p></div><button className="button neuron-signal" aria-pressed={signal} onClick={()=>{api.current?.signal();setSignal(!signal)}}>{signal?<Pause size={16}/>:<Play size={16}/>} {signal?'Pause signal':'Follow a nerve impulse'}</button><p className="neuron-caption">Signal animation is slowed and illustrative; neurons do not emit visible light.</p></aside></div><p className="model-credit">Anatomically informed artistic reconstruction, not a scan of an individual neuron. Branching, colors and proportions vary in living cells; axon length and fine details are adjusted for visibility. <a href="https://www.ninds.nih.gov/health-information/public-education/brain-basics/brain-basics-life-and-death-neuron" target="_blank" rel="noreferrer">Learn about neurons · NINDS <ArrowUpRight size={13}/></a></p></section>;
}
